[nginxdecoder]
type = "LoglineDecoder"
match_regex = '^(?P<RemoteIP>(?:\d{1,3}\.){3}\d{1,3}) (?P<Host>\S+) \S+ \[(?P<Timestamp>\d\d/\w{3}/\d{4}:\d\d:\d\d:\d\d) \+\d+\] "(?P<Method>\w+) (?P<Url>\S+) HTTP.+?" (?P<StatusCode>\d+) (?P<Bytes>\d+)'
timestamp_layout = '02/Jan/2006:15:04:05'

[nginxdecoder.message_fields]
Type = "nginx.logline"
RemoteIP|ipv4 = "%RemoteIP%"
Host = "%Host%"
Method = "%Method%"
Url|uri = "%Url%"
StatusCode = "%StatusCode%"
Bytes|B = "%Bytes%"
Payload = ""

[MktLogFileInput]
type = "LogfileInput"
logfile = "/var/log/nginx/marketplace.firefox.com/access.log"
logger = "nginx-mkt-prod"
decoders = ["nginxdecoder"]


[output]
type = "TcpOutput"
message_matcher = "Type == 'nginx.logline'"
address = "<%= log_host %>"
